:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_parameters)).
:- initialization main.

main():-
  server(1234).


server(Port) :-
        http_server(http_dispatch, [port(Port)]).
        
:- http_handler('/', func,[]).

:- http_handler('/prueba',test,[]).


test(_Request) :-
    format('Content-type: text/plain~n~n'),
    format('Hello World!~n').


func(Request) :-
    http_parameters(Request,[ msg(A,[ optional(true) ])]), 
    format('Content-type: text/plain~n~n'),
    split_string(A, "_", "", L),
    analizar(L,B),
    format('~p',B).



% Solo por probar

analizar(X,R):- printout(X,R).

printout([],"none").
printout(N,R):- word(N,R),!.
printout([N|Tail],R):- word(N,R) ; printout(Tail,R).

word("satan","religion").
word("satanismo","religion").
word("noe","religion").
word("arca","religion").
word("apocalipsis","religion").
word("resureccion","religion").
word("novio","religion").
word("anillo","religion").
word("promesa","religion").
word("promesas","religion").
word("solemne","religion").
word("solemnes","religion").
word("novia","religion").
word("novias","religion").
word("dama","religion").
word("honor","religion").
word("entierro","religion").
word("tumba","religion").
word("carro","religion").
word("funebre","religion").
word("lapida","religion").
word("lapidas","religion").
word("exequias","religion").
word("enterrar","religion").
word("enterrarlo","religion").
word("enterrarla","religion").
word("cementerio","religion").
word("cementerios","religion").
word("ataud","religion").
word("ataudes","religion").
word("imagen","religion").
word("imagenes","religion").
word("incineracion","religion").
word("lamentarse","religion").
word("arzobispo","religion").
word("arzobispos","religion").
word("diacono","religion").
word("diaconos","religion").
word("santo","religion").
word("santos","religion").
word("monja","religion").
word("monjas","religion").
word("abad","religion").
word("discipulo","religion").
word("discipulos","religion").
word("obispo","religion").
word("obispos","religion").
word("cura","religion").
word("curas","religion").
word("papa","religion").
word("papas","religion").
word("monje","religion").
word("monjes","religion").
word("cardinal","religion").
word("cardinales","religion").
word("peregrino","religion").
word("peregrinos","religion").
word("peregrinaje","religion").
word("capilla","religion").
word("capillas","religion").
word("campanario","religion").
word("camparanios","religion").
word("sacristia","religion").
word("sacristan","religion").
word("campana","religion").
word("navidad","religion").
word("navidades","religion").
word("cuaresma","religion").
word("cuaresmas","religion").
word("santa","religion").
word("semana","religion").
word("noche","religion").
word("buena","religion").
word("oracion","religion").
word("oraciones","religion").
word("apostol","religion").
word("biblia","religion").
word("blasfemia","religion").
word("blasfemico","religion").
word("blasfemica","religion").
word("bendecion","religion").
word("bendecir","religion").
word("bendiga","religion").
word("bendito","religion").
word("bendita","religion").
word("sotana","religion").
word("catedral","religion").
word("catedrales","religion").
word("catolico","religion").
word("catolicos","religion").
word("catolica","religion").
word("catolicas","religion").
word("catolicismo","religion").
word("caliz","religion").
word("caridad","religion").
word("coro","religion").
word("coros","religion").
word("confesion","religion").
word("confesiones","religion").
word("confirmacion","religion").
word("confirma","religion").
word("catequesis","religion").
word("fiel","religion").
word("fieles","religion").
word("romero","religion").
word("romeros","religion").
word("hostia","religion").
word("convento","religion").
word("conventos","religion").
word("comunion","religion").
word("dios","religion").
word("dioses","religion").
word("evangelio","religion").
word("aureola","religion").
word("aureolas","religion").
word("pagano","religion").
word("pagana","religion").
word("paganos","religion").
word("cielo","religion").
word("infierno","religion").
word("herejia","religion").
word("hereje","religion").
word("santidad","religion").
word("bendita","religion").
word("incienso","religion").
word("arrodillarse","religion").
word("pederasta","religion").
word("misa","religion").
word("ra","religion").
word("mahoma","religion").
word("buda","religion").
word("budismo","religion").
word("budaismo","religion").
word("coran","religion").
word("templo","religion").
word("templos","religion").
word("milagro","religion").
word("milagros","religion").
word("monasterio","religion").
word("parroquia","religion").
word("parroquias","religion").
word("parroquial","religion").
word("piedad","religion").
word("glorioso","religion").
word("gloriosa","religion").
word("lucifer","religion").
word("redencion","religion").
word("comulgar","religion").
word("comulgacion","religion").
word("adan","religion").
word("moises","religion").
word("eva","religion").
word("cruz","religion").
word("crucificcion","religion").
word("barrabas","religion").
word("predicar","religion").
word("salmo","religion").
word("evangelio","religion").
word("rosario","religion").
word("sermon","religion").
word("pecado","religion").
word("pecador","religion").
word("pecadora","religion").
word("sodomita","religion").
word("diablo","religion").
word("teologia","religion").
word("rezaradorar","religion").
word("matrimonio","religion").
word("vestiduras","religion").
word("juan","religion").
word("pablo","religion").
word("venedico","religion").
word("venedictus","religion").
word("diesciseis","religion").
word("francisco","religion").
word("primero","religion").
word("ateismo","religion").
word("ateo","religion").
word("atea","religion").
word("ateos","religion").
word("ateas","religion").
word("fe","religion").
word("creencia","religion").
word("espiritualidad","religion").
word("espiritual","religion").
word("espiritu","religion").
word("alma","religion").
word("santificado","religion").
word("reino","religion").
word("paraiso","religion").
word("filipenses","religion").
word("religion","religion").
word("religiones","religion").
word("esperanza","religion").
word("caridad","religion").
word("hermandad","religion").
word("hermandades","religion").
word("fraternidades","religion").
word("fraternidad","religion").
word("credo","religion").
word("creencias","religion").
word("sacrificio","religion").
word("bondad","religion").
word("creencia","religion").
word("dogma","religion").
word("9","religion").
word("evagenlio","religion").
word("cristiano","religion").
word("10","religion").
word("cristianismo","religion").
word("cristianos","religion").
word("crisitiana","religion").
word("culto","religion").
word("secta","religion").
word("ideología","religion").
word("devoto","religion").
word("piadoso","religion").
word("convecido","religion").
word("convecimiento","religion").
word("misericordioso","religion").
word("misericordia","religion").
word("virgen","religion").
word("fiel","religion").
word("fieles","religion").
word("clerico","religion").
word("confieso","religion").
word("confesarse","religion").
word("beato","religion").
word("doctrina","religion").
word("discipulo","religion").
word("adorar","religion").
word("adorador","religion").
word("adoracion","religion").
word("creyente","religion").
word("practicante","religion").
word("judio","religion").
word("judia","religion").
word("monaguillo","religion").
word("maniguilla","religion").
word("maniguillos","religion").
word("altar","religion").
word("arrodillarse","religion").
word("oracion","religion").
word("orar","religion").
word("rezador","religion").
word("5","religion").
word("rezar","religion").
word("sacramento","religion").
word("conviccion","religion").
word("8","religion").
word("iglesia","religion").
word("ense~anza","religion").
word("plegaria","religion").
word("benedicto","religion").
word("ungido","religion").
word("sacerdotal","religion").
word("sacerdote","religion").
word("sacerdotes","religion").
word("adorador","religion").
word("divinidad","religion").
word("religioso","religion").
word("religiosa","religion").
word("jehova","religion").
word("ovispo","religion").
word("pandereta","religion").
word("belzebu","religion").
word("religiosos","religion").
word("saprissa","futbol").
word("saprisistas","futbol").
word("alajuelense","futbol").
word("alajuelenses","futbol").
word("manudos","futbol").
word("manudo","futbol").
word("princesos","futbol").
word("sele","futbol").
word("messi","futbol").
word("cristiano","futbol").
word("ronaldo","futbol").
word("pipo","futbol").
word("fifa","futbol").
word("portero","futbol").
word("porteros","futbol").
word("delantero","futbol").
word("delanteros","futbol").
word("maleta","futbol").
word("bryan","futbol").
word("ruiz","futbol").
word("celso","futbol").
word("borges","futbol").
word("joel","futbol").
word("campbell","futbol").
word("alineacion","futbol").
word("alineaciones","futbol").
word("arbitro","futbol").
word("arbitros","futbol").
word("arco","futbol").
word("aficion","futbol").
word("aficiones","futbol").
word("aficionados","futbol").
word("aficionados","futbol").
word("marco","futbol").
word("marcos","futbol").
word("gol","futbol").
word("goles","futbol").
word("arquero","futbol").
word("autogol","futbol").
word("autogoles","futbol").
word("artillero","futbol").
word("artilleros","futbol").
word("autopase","futbol").
word("autopases","futbol").
word("autoservicio","futbol").
word("autoservicios","futbol").
word("balon","futbol").
word("balones","futbol").
word("banquillo","futbol").
word("banquillos","futbol").
word("camerino","futbol").
word("camerinos","futbol").
word("taco","futbol").
word("tacos","futbol").
word("cabecear","futbol").
word("cabeceo","futbol").
word("cabeceos","futbol").
word("calentar","futbol").
word("calentamiento","futbol").
word("calentamientos","futbol").
word("cambio","futbol").
word("cambios","futbol").
word("campeon","futbol").
word("campeones","futbol").
word("campeonato","futbol").
word("campeonatos","futbol").
word("invierno","futbol").
word("cueva","futbol").
word("liga","futbol").
word("heredia","futbol").
word("herediano","futbol").
word("hala","futbol").
word("madrid","futbol").
word("monstruo","futbol").
word("leon","futbol").
word("casa","futbol").
word("cancerbero","futbol").
word("cancerberos","futbol").
word("cancha","futbol").
word("canchas","futbol").
word("capitan","futbol").
word("capitanes","futbol").
word("capi","futbol").
word("amarilla","futbol").
word("amarillas","futbol").
word("rojas","futbol").
word("roja","futbol").
word("central","futbol").
word("centrales","futbol").
word("centrocampista","futbol").
word("centrocampistas","futbol").
word("cesped","futbol").
word("grama","futbol").
word("gramillas","futbol").
word("gramilla","futbol").
word("clasificacion","futbol").
word("clasificaciones","futbol").
word("club","futbol").
word("clubes","futbol").
word("cobertura","futbol").
word("coberturas","futbol").
word("colegiado","futbol").
word("colegiados","futbol").
word("concacaf","futbol").
word("convocar","futbol").
word("convocados","futbol").
word("convocatoria","futbol").
word("convocatorias","futbol").
word("copa","futbol").
word("copas","futbol").
word("corner","futbol").
word("corners","futbol").
word("crack","futbol").
word("cracks","futbol").
word("tecnico","futbol").
word("tecnicos","futbol").
word("final","futbol").
word("finales","futbol").
word("descanso","futbol").
word("descansos","futbol").
word("debutar","futbol").
word("debutantes","futbol").
word("defensas","futbol").
word("adelantada","futbol").
word("defensa","futbol").
word("definicion","futbol").
word("definiciones","futbol").
word("delantera","futbol").
word("delanteras","futbol").
word("delantero","futbol").
word("delanteros","futbol").
word("deportivo","futbol").
word("deportivos","futbol").
word("derechazo","futbol").
word("derechazos","futbol").
word("derrota","futbol").
word("derrotas","futbol").
word("descanso","futbol").
word("descender","futbol").
word("desequilibrar","futbol").
word("desequilibrante","futbol").
word("desequilibrantes","futbol").
word("designacion","futbol").
word("desmarque","futbol").
word("despejar","futbol").
word("desplazamiento","futbol").
word("desplazamientos","futbol").
word("destitucion","futbol").
word("destituciones","futbol").
word("desviar","futbol").
word("desvios","futbol").
word("detener","futbol").
word("duarte","futbol").
word("oscar","futbol").
word("machillo","futbol").
word("ramirez","futbol").
word("pate","futbol").
word("douglas","futbol").
word("sequeira","futbol").
word("diagonal","futbol").
word("diagonales","futbol").
word("diana","futbol").
word("dianas","futbol").
word("diestro","futbol").
word("dinamico","futbol").
word("dinamicos","futbol").
word("disparo","futbol").
word("disparos","futbol").
word("distribuir","futbol").
word("dopaje","futbol").
word("dopajes","futbol").
word("dorsal","futbol").
word("driblar","futbol").
word("efectividad","futbol").
word("efecto","futbol").
word("efectos","futbol").
word("goleadora","futbol").
word("goleadoras","futbol").
word("eje","futbol").
word("ejes","futbol").
word("eliminar","futbol").
word("eliminatoria","futbol").
word("eliminatorias","futbol").
word("empatar","futbol").
word("empate","futbol").
word("empates","futbol").
word("empeine","futbol").
word("encajar","futbol").
word("encerrarse","futbol").
word("encerrona","futbol").
word("entrada","futbol").
word("entradas","futbol").
word("entrega","futbol").
word("entregas","futbol").
word("entrenador","futbol").
word("entrenadores","futbol").
word("entrenamiento","futbol").
word("entrenamientos","futbol").
word("equipo","futbol").
word("equipos","futbol").
word("titular","futbol").
word("titulares","futbol").
word("escuadra","futbol").
word("escuadras","futbol").
word("escudo","futbol").
word("escudos","futbol").
word("esferico","futbol").
word("esfericos","futbol").
word("espinilleras","futbol").
word("estadio","futbol").
word("estadios","futbol").
word("nacional","futbol").
word("sabana","futbol").
word("estrategia","futbol").
word("estrategias","futbol").
word("estratega","futbol").
word("estrategas","futbol").
word("expulsar","futbol").
word("expulsiones","futbol").
word("expulsado","futbol").
word("expulsados","futbol").
word("fair","futbol").
word("falta","futbol").
word("faltas","futbol").
word("federacion","futbol").
word("federaciones","futbol").
word("fichar","futbol").
word("fichajes","futbol").
word("finalista","futbol").
word("finalistas","futbol").
word("finta","futbol").
word("fintas","futbol").
word("frontal","futbol").
word("frontales","futbol").
word("juego","futbol").
word("juegos","futbol").
word("fusilar","futbol").
word("futbol","futbol").
word("gambeta","futbol").
word("gambetas","futbol").
word("gambetear","futbol").
word("jugador","futbol").
word("jugadores","futbol").
word("comite","futbol").
word("comites","futbol").
word("globo","futbol").
word("globos","futbol").
word("anulado","futbol").
word("anulados","futbol").
word("average","futbol").
word("asistencia","futbol").
word("asistencias","futbol").
word("oro","futbol").
word("oros","futbol").
word("goleador","futbol").
word("goleadores","futbol").
word("golear","futbol").
word("goleada","futbol").
word("guardameta","futbol").
word("guardametas","futbol").
word("hattrick","futbol").
word("himno","futbol").
word("himnos","futbol").
word("hueco","futbol").
word("huecos","futbol").
word("imbatido","futbol").
word("imbatidos","futbol").
word("imparable","futbol").
word("imparables","futbol").
word("inauguracion","futbol").
word("inauguraciones","futbol").
word("incorporacion","futbol").
word("incorporaciones","futbol").
word("incursion","futbol").
word("incursiones","futbol").
word("individualista","futbol").
word("individualistas","futbol").
word("infiltrar","futbol").
word("infraccion","futbol").
word("infracciones","futbol").
word("interceptar","futbol").
word("interceptaron","futbol").
word("interior","futbol").
word("interiores","futbol").
word("intermediario","futbol").
word("intermediarios","futbol").
word("internacional","futbol").
word("internacionales","futbol").
word("invicto","futbol").
word("invictos","futbol").
word("jornada","futbol").
word("jornadas","futbol").
word("aereo","futbol").
word("aereos","futbol").
word("limpio","futbol").
word("limpios","futbol").
word("peligroso","futbol").
word("peligrosos","futbol").
word("peligro","futbol").
word("peligros","futbol").
word("sucio","futbol").
word("sucios","futbol").
word("juez","futbol").
word("jueces","futbol").
word("jugada","futbol").
word("jugadas","futbol").
word("ensayada","futbol").
word("ensayadas","futbol").
word("doce","futbol").
word("patadon","futbol").
word("patadas","futbol").
word("lanzamientos","futbol").
word("lanzamiento","futbol").
word("larguero","futbol").
word("lateral","futbol").
word("laterales","futbol").
word("lesion","futbol").
word("lesiones","futbol").
word("compensacion","futbol").
word("compensaciones","futbol").
word("ventaja","futbol").
word("ventajas","futbol").
word("lider","futbol").
word("lideres","futbol").
word("liderato","futbol").
word("lideratos","futbol").
word("linea","futbol").
word("lineas","futbol").
word("local","futbol").
word("locales","futbol").
word("luminoso","futbol").
word("luminosos","futbol").
word("racha","futbol").
word("rachas","futbol").
word("record","futbol").
word("records","futbol").
word("maletin","futbol").
word("maletines","futbol").
word("mallas","futbol").
word("malla","futbol").
word("manager","futbol").
word("managers","futbol").
word("manita","futbol").
word("manitas","futbol").
word("mano","futbol").
word("manos","futbol").
word("bombo","futbol").
word("bombos","futbol").
word("platillos","futbol").
word("marcador","futbol").
word("marcadores","futbol").
word("marcaje","futbol").
word("marcajes","futbol").
word("marcar","futbol").
word("matador","futbol").
word("matagigantes","futbol").
word("maxima","futbol").
word("maximo","futbol").
word("medialuna","futbol").
word("mediapunta","futbol").
word("mediapuntas","futbol").
word("media","futbol").
word("medias","futbol").
word("medias","futbol").
word("medio","futbol").
word("medios","futbol").
word("mediocampo","futbol").
word("mediocampos","futbol").
word("contrato","futbol").
word("contratos","futbol").
word("mercado","futbol").
word("mercados","futbol").
word("mercenario","futbol").
word("camiseta","futbol").
word("camisetas","futbol").
word("clasico","futbol").
word("clasicos","futbol").
word("practica","futbol").
word("practicas","futbol").
word("medirse","futbol").
word("similar","futbol").
word("rival","futbol").
word("rivales","futbol").
word("mercenarios","futbol").
word("meta","futbol").
word("metas","futbol").
word("misil","futbol").
word("misiles","futbol").
word("mister","futbol").
word("mixto","futbol").
word("mixtos","futbol").
word("minutos","futbol").
word("minuto","futbol").
word("mojar","futbol").
word("moral","futbol").
word("mundial","futbol").
word("mundiales","futbol").
word("mundialito","futbol").
word("mundialitos","futbol").
word("nacionalizado","futbol").
word("nacionalizados","futbol").
word("naranja","futbol").
word("naranjas","futbol").
word("mecanica","futbol").
word("negativos","futbol").
word("negativo","futbol").
word("negociar","futbol").
word("negociando","futbol").
word("obstruccion","futbol").
word("obstrucciones","futbol").
word("ocasion","futbol").
word("ocasiones","futbol").
word("olfato","futbol").
word("manifiesta","futbol").
word("octavos","futbol").
word("primero","futbol").
word("oferta","futbol").
word("ofertas","futbol").
word("offside","futbol").
word("ofrecerse","futbol").
word("ofrecimiento","futbol").
word("ofrecimientos","futbol").
word("goleador","futbol").
word("goleadores","futbol").
word("once","futbol").
word("opcion","futbol").
word("opciones","futbol").
word("oportunidad","futbol").
word("oportunidades","futbol").
word("orey","futbol").
word("organizador","futbol").
word("organizadores","futbol").
word("oriundo","futbol").
word("oriundos","futbol").
word("outsider","futbol").
word("oyente","futbol").
word("oyentes","futbol").
word("palco","futbol").
word("palcos","futbol").
word("paliza","futbol").
word("palizas","futbol").
word("palo","futbol").
word("palos","futbol").
word("corto","futbol").
word("cortos","futbol").
word("largo","futbol").
word("largos","futbol").
word("palomero","futbol").
word("palomeros","futbol").
word("palomita","futbol").
word("palomitas","futbol").
word("pancarta","futbol").
word("pancartas","futbol").
word("pantalon","futbol").
word("pantalones","futbol").
word("paquete","futbol").
word("paquetes","futbol").
word("parabola","futbol").
word("parabolas","futbol").
word("parada","futbol").
word("paradas","futbol").
word("pared","futbol").
word("paredes","futbol").
word("pareja","futbol").
word("parejas","futbol").
word("atacante","futbol").
word("atacantes","futbol").
word("parte","futbol").
word("partes","futbol").
word("partido","futbol").
word("partidos","futbol").
word("amistoso","futbol").
word("amistosos","futbol").
word("comprado","futbol").
word("comprados","futbol").
word("ida","futbol").
word("idas","futbol").
word("pase","futbol").
word("pases","futbol").
word("largo","futbol").
word("pasillos","futbol").
word("pasillo","futbol").
word("patada","futbol").
word("patadas","futbol").
word("patrocinador","futbol").
word("patrocinadores","futbol").
word("pay-per-view","futbol").
word("pechito","futbol").
word("pegada","futbol").
word("pegadas","futbol").
word("peinar","futbol").
word("pelota","futbol").
word("pelotas","futbol").
word("pena","futbol").
word("penas","futbol").
word("maxima","futbol").
word("maximas","futbol").
word("penalizar","futbol").
word("penalizaciones","futbol").
word("penalty","futbol").
word("penalties","futbol").
word("penetracion","futbol").
word("penetraciones","futbol").
word("pentacampeon","futbol").
word("pentacampeones","futbol").
word("pepinazo","futbol").
word("pepinazos","futbol").
word("tiempo","futbol").
word("tiempos","futbol").
word("perdonar","futbol").
word("permanencia","futbol").
word("permanencias","futbol").
word("peto","futbol").
word("petos","futbol").
word("pique","futbol").
word("piques","futbol").
word("piscinazo","futbol").
word("piscinazos","futbol").
word("piso","futbol").
word("pisos","futbol").
word("pisoton","futbol").
word("pisotones","futbol").
word("pitada","futbol").
word("pitadas","futbol").
word("pitar","futbol").
word("pito","futbol").
word("pitos","futbol").
word("planteamiento","futbol").
word("planteamientos","futbol").
word("play-off","futbol").
word("polideportivo","futbol").
word("polideportivos","futbol").
word("porra","futbol").
word("porras","futbol").
word("porteria","futbol").
word("porterias","futbol").
word("suplente","futbol").
word("suplentes","futbol").
word("posicion","futbol").
word("posiciones","futbol").
word("adelantada","futbol").
word("adelantadas","futbol").
word("poste","futbol").
word("postes","futbol").
word("premier-league","futbol").
word("preparador","futbol").
word("preparadores","futbol").
word("fisico","futbol").
word("fisicos","futbol").
word("presidente","futbol").
word("presidentes","futbol").
word("presion","futbol").
word("presiones","futbol").
word("presupuesto","futbol").
word("presupuestos","futbol").
word("pretemporada","futbol").
word("pretemporadas","futbol").
word("division","futbol").
word("divisiones","futbol").
word("primera","futbol").
word("primeras","futbol").
word("puntapie","futbol").
word("puntapies","futbol").
word("punteria","futbol").
word("punterias","futbol").
word("penal","futbol").
word("penales","futbol").
word("punto","futbol").
word("puntos","futbol").
word("racha","futbol").
word("rachas","futbol").
word("reaccionar","futbol").
word("reacciones","futbol").
word("rebote","futbol").
word("rebotes","futbol").
word("recibir","futbol").
word("recogepelotas","futbol").
word("reglamento","futbol").
word("reglamentos","futbol").
word("rematar","futbol").
word("remates","futbol").
word("remate","futbol").
word("remontada","futbol").
word("remontadas","futbol").
word("remontar","futbol").
word("representante","futbol").
word("representantes","futbol").
word("resultado","futbol").
word("resultados","futbol").
word("retencion","futbol").
word("retenciones","futbol").
word("titulo","futbol").
word("titulos","futbol").
word("reventa","futbol").
word("reventas","futbol").
word("rival","futbol").
word("rivales","futbol").
word("directo","futbol").
word("directos","futbol").
word("rivalidad","futbol").
word("rivalidades","futbol").
word("ronda","futbol").
word("tricolor","futbol").
word("gane","futbol").
word("ganes","futbol").
word("antidopaje","futbol").
word("premundial","futbol").
word("ganar","futbol").
word("antidopajes","futbol").
word("doping","futbol").
word("rondas","futbol").
word("preeliminar","futbol").
word("preeliminares","futbol").
word("sacar","futbol").
word("prensa","futbol").
word("prensas","futbol").
word("saque","futbol").
word("saques","futbol").
word("banda","futbol").
word("bandas","futbol").
word("puerta","futbol").
word("puertas","futbol").
word("seleccion","futbol").
word("selecciones","futbol").
word("nacional","futbol").
word("nacionales","futbol").
word("selecionador","futbol").
word("selecionadores","futbol").
word("semifinal","futbol").
word("semifinales","futbol").
word("sentenciar","futbol").
word("sentencias","futbol").
word("doble","futbol").
word("dobles","futbol").
word("siete","futbol").
word("silbidos","futbol").
word("silbido","futbol").
word("simpatizante","futbol").
word("simpatizantes","futbol").
word("simular","futbol").
word("barrera","futbol").
word("barreras","futbol").
word("muscular","futbol").
word("musculares","futbol").
word("soccer","futbol").
word("sombrero","futbol").
word("sombreros","futbol").
word("sorteo","futbol").
word("sorteos","futbol").
word("subcampeon","futbol").
word("subcampeones","futbol").
word("supercopa","futbol").
word("supercopas","futbol").
word("taquito","futbol").
word("taquitos","futbol").
word("tanda","futbol").
word("tandas","futbol").
word("tanto","futbol").
word("tantos","futbol").
word("tarjeta","futbol").
word("tarjetas","futbol").
word("terreno","futbol").
word("terrenos","futbol").
word("tetracampeon","futbol").
word("tetracampeones","futbol").
word("tiro","futbol").
word("tiros","futbol").
word("libre","futbol").
word("libres","futbol").
word("tobillera","futbol").
word("tobilleras","futbol").
word("torneo","futbol").
word("torneos","futbol").
word("verano","futbol").
word("veranos","futbol").
word("invierno","futbol").
word("inviernos","futbol").
word("travesa~o","futbol").
word("travesa~os","futbol").
word("trayectoria","futbol").
word("trayectorias","futbol").
word("tricampeon","futbol").
word("tricampeones","futbol").
word("arbitral","futbol").
word("arbitrales","futbol").
word("triplete","futbol").
word("tripletes","futbol").
word("ultra","futbol").
word("ultras","futbol").
word("morado","futbol").
word("morados","futbol").
word("rojinegro","futbol").
word("rojinegros","futbol").
word("visita","futbol").
word("visitas","futbol").
word("visitante","futbol").
word("visitantes","futbol").
word("volante","futbol").
word("volantes","futbol").
word("zaga","futbol").
word("zagas","futbol").
word("zaguero","futbol").
word("zagueros","futbol").
word("zancadilla","futbol").
word("zancadillas","futbol").
word("zurdazo","futbol").
word("zurdazos","futbol").
word("ï»¿direccion","politica").
word("direcciones","politica").
word("guia","politica").
word("guias","politica").
word("gobierno","politica").
word("gobiernos","politica").
word("estatal","politica").
word("estatales","politica").
word("estado","politica").
word("estados","politica").
word("geopolitica","politica").
word("geopoliticas","politica").
word("politica","politica").
word("politicas","politica").
word("social","politica").
word("sociales","politica").
word("diplomacia","politica").
word("diplomacias","politica").
word("partido","politica").
word("partidos","politica").
word("fraccion","politica").
word("fracciones","politica").
word("politico","politica").
word("politica","politica").
word("politicos","politica").
word("politicas","politica").
word("bando","politica").
word("banda","politica").
word("doctrina","politica").
word("doctirnas","politica").
word("grupo","politica").
word("grupos","politica").
word("secta","politica").
word("sectas","politica").
word("asociacion","politica").
word("asociaciones","politica").
word("agrupacion","politica").
word("agrupaciones","politica").
word("creencia","politica").
word("creencias","politica").
word("credo","politica").
word("credos","politica").
word("idea","politica").
word("ideas","politica").
word("ideologia","politica").
word("ideologias","politica").
word("opinion","politica").
word("opiniones","politica").
word("equipo","politica").
word("equipos","politica").
word("congregacion","politica").
word("congregaciones","politica").
word("banderia","politica").
word("banderias","politica").
word("tendencia","politica").
word("tendencias","politica").
word("ideologia","politica").
word("ideologias","politica").
word("liberalismo","politica").
word("progresismo","politica").
word("democracia","politica").
word("democracias","politica").
word("izquierda","politica").
word("izquierdas","politica").
word("izquierdismo","politica").
word("socialismo","politica").
word("comunista","politica").
word("comunistas","politica").
word("comunismo","politica").
word("marxismo","politica").
word("soviet","politica").
word("maoismo","politica").
word("bolchevismo","politica").
word("obrerismo","politica").
word("sindicalismo","politica").
word("estajanovismo","politica").
word("trotskismo","politica").
word("laborismo","politica").
word("reformismo","politica").
word("reforma","politica").
word("radicalismo","politica").
word("legitimismo","politica").
word("republicanismo","politica").
word("republicano","politica").
word("anarquismo","politica").
word("anarquista","politica").
word("nihilismo","politica").
word("centrismo","politica").
word("democracia","politica").
word("monarquismo","politica").
word("monarca","politica").
word("monarcas","politica").
word("conservadurismo","politica").
word("centralismo","politica").
word("integrismo","politica").
word("derechismo","politica").
word("derecha","politica").
word("derecho","politica").
word("colonialismo","politica").
word("militarismo","politica").
word("carlismo","politica").
word("clericalismo","politica").
word("imperialismo","politica").
word("imperial","politica").
word("reaccion","politica").
word("reacciones","politica").
word("capitalismo","politica").
word("capitalista","politica").
word("capitalistas","politica").
word("falangismo","politica").
word("fascismo","politica").
word("fascista","politica").
word("fascistas","politica").
word("nazismo","politica").
word("nazi","politica").
word("nazis","politica").
word("pangermanismo","politica").
word("nacionalismo","politica").
word("nacion","politica").
word("naciones","politica").
word("legitimismo","politica").
word("autonomismo","politica").
word("federalismo","politica").
word("separatismo","politica").
word("expansionismo","politica").
word("expansion","politica").
word("revolucion","politica").
word("revoluciones","politica").
word("intervencionismo","politica").
word("belicismo","politica").
word("terrorismo","politica").
word("terrorista","politica").
word("terroristas","politica").
word("extremismo","politica").
word("caciquismo","politica").
word("feminismo","politica").
word("feminista","politica").
word("feministas","politica").
word("sionismo","politica").
word("panarabismo","politica").
word("neutralismo","politica").
word("neutral","politica").
word("pacifismo","politica").
word("pacifico","politica").
word("pacificos","politica").
word("demagogia","politica").
word("despotismo","politica").
word("despota","politica").
word("despotas","politica").
word("mixtificacion","politica").
word("regimenes","politica").
word("regimen","politica").
word("constitucional","politica").
word("constitucionales","politica").
word("parlamentario","politica").
word("economico","politica").
word("economia","politica").
word("representativo","politica").
word("representativos","politica").
word("representativa","politica").
word("popular","politica").
word("populares","politica").
word("unicameral","politica").
word("bicameral","politica").
word("presidencialista","politica").
word("presidente","politica").
word("absolutista","politica").
word("colonialista","politica").
word("sindicalista","politica").
word("gobierno","politica").
word("gobiernos","politica").
word("autonomo","politica").
word("autonomos","politica").
word("autonoma","politica").
word("autonomas","politica").
word("federal","politica").
word("federales","politica").
word("asociado","politica").
word("asociados","politica").
word("asociada","politica").
word("libre","politica").
word("libres","politica").
word("separado","politica").
word("separados","politica").
word("separadas","politica").
word("tecnocracia","politica").
word("burocracia","politica").
word("autocracia","politica").
word("autarquia","politica").
word("monarquia","politica").
word("monarquias","politica").
word("monarca","politica").
word("monarcas","politica").
word("regencia","politica").
word("republica","politica").
word("republicas","politica").
word("imperio","politica").
word("imperios","politica").
word("plutocracia","politica").
word("tirania","politica").
word("tirano","politica").
word("tiranos","politica").
word("oligarquia","politica").
word("gerontocracia","politica").
word("matriarcado","politica").
word("aristocracia","politica").
word("patriciado","politica").
word("consulado","politica").
word("consulados","politica").
word("triunvirato","politica").
word("tetrarquia","politica").
word("junta","politica").
word("juntas","politica").
word("directorio","politica").
word("directorios","politica").
word("mancomunidad","politica").
word("colaboracionismo","politica").
word("plebiscito","politica").
word("referendum","politica").
word("eleccion","politica").
word("elecciones","politica").
word("votaciones","politica").
word("votacion","politica").
word("voto","politica").
word("sufragio","politica").
word("opinion","politica").
word("publica","politica").
word("campa~a","politica").
word("campa~as","politica").
word("propaganda","politica").
word("propagandas","politica").
word("electoral","politica").
word("discurso","politica").
word("discursos","politica").
word("mitin","politica").
word("nacion","politica").
word("naciones","politica").
word("estado","politica").
word("estados","politica").
word("institucion","politica").
word("instituciones","politica").
word("civismo","politica").
word("oposicion","politica").
word("oposiciones","politica").
word("guerra","politica").
word("guerras","politica").
word("fria","politica").
word("gobernador","politica").
word("gobernantes","politica").
word("ministro","politica").
word("ministros","politica").
word("diputado","politica").
word("diputados","politica").
word("asambleista","politica").
word("asambleistas","politica").
word("congresista","politica").
word("congresista","politica").
word("partidario","politica").
word("correligionario","politica").
word("militante","politica").
word("oponente","politica").
word("oponentes","politica").
word("adversario","politica").
word("adversarios","politica").
word("politicastro","politica").
word("activista","politica").
word("agitador","politica").
word("revolucionario","politica").
word("revolucionarios","politica").
word("moderado","politica").
word("moderados","politica").
word("avanzado","politica").
word("avanzados","politica").
word("radical","politica").
word("radicales","politica").
word("democrata","politica").
word("democratas","politica").
word("socialista","politica").
word("socialistas","politica").
word("gubernativo","politica").
word("gubernamental","politica").
word("gubernamentales","politica").
word("oscar","politica").
word("arias","politica").
word("johnny","politica").
word("araya","politica").
word("rolando","politica").
word("otto","politica").
word("guevarra","politica").
word("guth","politica").
word("villalta","politica").
word("figueres","politica").
word("olsen","politica").
word("oton","politica").
word("chinchilla","politica").
word("laura","politica").
word("pacheco","politica").
word("luis","politica").
word("guillermo","politica").
word("solis","politica").
word("monge","politica").
word("obama","politica").
word("maduro","politica").
word("ortega","politica").
word("nicas","politica").
word("nica","politica").
word("dilma","politica").
word("abraham","politica").
word("franklin","politica").
word("george","politica").
word("washington","politica").
word("mackinley","politica").
word("nixon","politica").
word("echandi","politica").
word("carazo","politica").
word("osama","politica").
word("ladden","politica").
word("schwarzenegger","politica").
word("reagan","politica").
word("clinton","politica").
word("trump","politica").
word("jefferson","politica").
word("zapatero","politica").
word("fidel","politica").
word("frontera","politica").
word("fronteras","politica").
word("vladimir","politica").
word("putin","politica").
word("mattarella","politica").
word("roosevelt","politica").
word("corrupcion","politica").
word("santamaria","politica").
word("rivas","politica").
word("pase","politica").
word("pln","politica").
word("pac","politica").
word("pusc","politica").
word("pfa","politica").
word("recope","politica").
word("ml","politica").
word("gorgojo","chistes").
word("porcio","chistes").
word("cuatrufia","chistes").
word("elodia","chistes").
word("colocho","chistes").
word("colochos","chistes").
word("bufon","chistes").
word("comediante","chistes").
word("comico","chistes").
word("comicos","chistes").
word("enredos","chistes").
word("enredo","chistes").
word("birra","chistes").
word("socao","chistes").
word("vacilon","chistes").
word("vacilones","chistes").
word("cucurucho","chistes").
word("cucurochos","chistes").
word("cacheton","chistes").
word("cachete","chistes").
word("checheres","chistes").
word("cachetere","chistes").
word("cachetero","chistes").
word("chechere","chistes").
word("enconchar","chistes").
word("enclocharon","chistes").
word("diversion","chistes").
word("menecazo","chistes").
word("menecos","chistes").
word("meneco","chistes").
word("meneca","chistes").
word("menecas","chistes").
word("cajada","chistes").
word("carajadas","chistes").
word("camote","chistes").
word("camotes","chistes").
word("bichillo","chistes").
word("bichillos","chistes").
word("broncon","chistes").
word("bruto","chistes").
word("brutos","chistes").
word("bruta","chistes").
word("brutas","chistes").
word("ba~aso","chistes").
word("ba~asos","chistes").
word("carajillo","chistes").
word("chimao","chistes").
word("chimaos","chistes").
word("chingo","chistes").
word("chingos","chistes").
word("chiverre","chistes").
word("chocho","chistes").
word("chochos","chistes").
word("chorizo","chistes").
word("chorizos","chistes").
word("chuchinga","chistes").
word("chuchingas","chistes").
word("chueco","chistes").
word("comedia","chistes").
word("chuecos","chistes").
word("joder","chistes").
word("jodieron","chistes").
word("pasta","chistes").
word("patatus","chistes").
word("payasada","chistes").
word("payaso","chistes").
word("payasa","chistes").
word("pelada","chistes").
word("paracaidista","chistes").
word("paracaidistas","chistes").
word("polos","chistes").
word("polo","chistes").
word("polada","chistes").
word("loco","chistes").
word("locos","chistes").
word("loca","chistes").
word("locas","chistes").
word("loquera","chistes").
word("trilonca","chistes").
word("chingue","chistes").
word("churuco","chistes").
word("coco","chistes").
word("corrongo","chistes").
word("corrongos","chistes").
word("corronguera","chistes").
word("estampa","chistes").
word("presa","chistes").
word("presas","chistes").
word("guato","chistes").
word("harina","chistes").
word("highlux","chistes").
word("feriado","chistes").
word("chavalo","chistes").
word("chavala","chistes").
word("carambada","chistes").
word("carambadas","chistes").
word("chilazo","chistes").
word("chilaso","chistes").
word("chile","chistes").
word("gracioso","chistes").
word("gosando","chistes").
word("chunche","chistes").
word("chinchorro","chistes").
word("chiste","chistes").
word("chistes","chistes").
word("descochero","chistes").
word("decocheraron","chistes").
word("feliz","chistes").
word("entretenido","chistes").
word("alegre","chistes").
word("teresa","chistes").
word("teresas","chistes").
word("bolichas","chistes").
word("bolincha","chistes").
word("reir","chistes").
word("risa","chistes").
word("lelo","chistes").
word("lelos","chistes").
word("tontera","chistes").
word("tonteras","chistes").
word("humor","chistes").
word("humorista","chistes").
word("humoristas","chistes").
word("huevon","chistes").
word("hueva","chistes").
word("huevaso","chistes").
word("sobaco","chistes").
word("sobacos","chistes").
word("paja","chistes").
word("pajas","chistes").
word("parandas","chistes").
word("paranda","chistes").
word("jaibo","chistes").
word("jeton","chistes").
word("jeta","chistes").
word("jetones","chistes").
word("juanvainas","chistes").
word("jupon","chistes").
word("jumas","chistes").
word("jupa","chistes").
word("fumas","chistes").
word("litrogeno","chistes").
word("nave","chistes").
word("pacho","chistes").
word("palmar","chistes").
word("palme","chistes").
word("palmaron","chistes").
word("perol","chistes").
word("pichirilo","chistes").
word("pepiodo","chistes").
word("pepis","chistes").
word("pinta","chistes").
word("piolin","chistes").
word("prole","chistes").
word("lechero","chistes").
word("tanda","chistes").
word("timba","chistes").
word("ticolandia","chistes").
word("maicero","chistes").
word("maiceros","chistes").
word("moncha","chistes").
word("pacheco","chistes").
word("pelon","chistes").
word("ruliar","chistes").
word("jamar","chistes").
word("jama","chistes").
word("jacha","chistes").
word("trolear","chistes").
word("chaniar","chistes").
word("agarrado","chistes").
word("apiar","chistes").
word("guayaba","chistes").
word("arrojar","chistes").
word("bochinche","chistes").
word("bombeta","chistes").
word("chaine","chistes").
word("chapa","chistes").
word("picaron","chistes").
word("picaro","chistes").
word("picara","chistes").
word("picaras","chistes").
word("yeyo","chistes").
word("tarro","chistes").
word("vaina","chistes").
word("tambo","chistes").
word("torre","chistes").
word("tostado","chistes").
word("tucas","chistes").
word("serte","chistes").
word("lol","chistes").
word("xd","chistes").
word("zarpe","chistes").
word("saborsh","chistes").
word("jajaja","chistes").
word("jaja","chistes").
word("hahaha","chistes").
word("haha","chistes").
word("jejeje","chistes").
word("jeje","chistes").
word("troll","chistes").
word("zaah","chistes").



